### ISSUE TITLE
Folk 设置完成之后会遇到编译错误

### ISSUE THREAD

**Issue by olddonkey** [draco-china/Draco-OpenWrt-GL-AX1800#15]
https://pipelines.actions.githubusercontent.com/serviceHosts/6c0b95d4-040d-455a-8a29-8dac37132340/_apis/pipelines/1/runs/29/signedlogcontent/2?urlExpires=2022-11-21T21%3A14%3A29.2391251Z&urlSigningMethod=HMACV1&urlSignature=kpb%2F%2FSOrrMvJPcWdaMIpl1UqPgyprUHOBmZc9hRw1Eg%3D

错误看起来是c++ 17的，但是不是很理解为什么在原始的repo里可以完成编译，是有环境变量设置问题么？

**Comment by smilekevin** [comment]
looks it is caused by runner on GitHub has been updated to 22.04
https://github.blog/changelog/2022-08-09-github-actions-ubuntu-22-04-is-now-generally-available-on-github-hosted-runners/

trying with patch on all the yml files. 

```
 jobs:
   build:
-    runs-on: ubuntu-latest
+    runs-on: ubuntu-20.04
```

**Comment by smilekevin** [comment]
> looks it is caused by runner on GitHub has been updated to 22.04 https://github.blog/changelog/2022-08-09-github-actions-ubuntu-22-04-is-now-generally-available-on-github-hosted-runners/
> 
> trying with patch on all the yml files.
> 
> ```
>  jobs:
>    build:
> -    runs-on: ubuntu-latest
> +    runs-on: ubuntu-20.04
> ```

it worked

**Comment by smilekevin** [comment]
also need update workflow.tpl file.

**Comment by olddonkey** [comment]
应该还漏了一个.github/workflows/generate-config.yml里面的版本号。

不过似乎还是不能完全解决问题，如果现在添加一些新的packages，因为版本问题，还是会编译失败， 例如

https://github.com/olddonkey/Draco-OpenWrt-GL-AX1800/actions/runs/3549319973

添加了ssr和passwall

**Comment by draco-china** [comment]
主要是多个插件依赖库版本没法一致

**Comment by draco-china** [comment]
建议fork之后先正常通过一次，然后自行修改需要的和不需要的插件

**Comment by yizhiheng** [comment]
我也遇到了同样的问题, 正在尝试只在`package.js`里enable `luci-app-ssr-plus` 看能不能build通过

**Comment by draco-china** [comment]
酸酸乳之类的科学插件 建议只上一个
