### ISSUE TITLE
不识别TF卡是什么问题？

### ISSUE THREAD

**Issue by yese1818** [draco-china/Draco-OpenWrt-GL-AX1800#21]
TF卡ext4格式，原厂AXT1800固件可以识别，刷了大佬这个固件后就不识别了。

**Comment by draco-china** [comment]
官方固件可能没支持

**Comment by yese1818** [comment]
是我错了，我把AX1800的固件装到了AXT1800的机器上，所以不能识别TF卡，换了另一个AXT1800的固件（非官方）就正常了。
