### ISSUE TITLE
MT2500固件的几个问题

### ISSUE THREAD

**Issue by cerellean** [draco-china/Draco-OpenWrt-GL-AX1800#24]
1、agron主题设置报错，建议弃用
/usr/lib/lua/luci/model/cbi/argon-config.lua:3: module 'luci.model.ipkg' not found:
	no field package.preload['luci.model.ipkg']
	no file './luci/model/ipkg.lua'
	no file '/usr/share/lua/luci/model/ipkg.lua'
	no file '/usr/share/lua/luci/model/ipkg/init.lua'
	no file '/usr/lib/lua/luci/model/ipkg.lua'
	no file '/usr/lib/lua/luci/model/ipkg/init.lua'
	no file './luci/model/ipkg.so'
	no file '/usr/lib/lua/luci/model/ipkg.so'
	no file '/usr/lib/lua/loadall.so'
	no file './luci.so'
	no file '/usr/lib/lua/luci.so'
	no file '/usr/lib/lua/loadall.so'
stack traceback:
	[C]: in function 'require'
	/usr/lib/lua/luci/model/cbi/argon-config.lua:3: in function 'func'
	/usr/lib/lua/luci/cbi.lua:66: in function 'load'
	/usr/lib/lua/luci/dispatcher.lua:1499: in function '_form'
	/usr/lib/lua/luci/dispatcher.lua:1027: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:479: in function </usr/lib/lua/luci/dispatcher.lua:478>

2、CPU 性能优化调节设置好像不支持，建议弃用。
3、OPKG安装的DDNS好像中文支持有问题

建议增加UPNP、DDNS、SSRP、KMS、网易云音乐这些实用插件

**Comment by pzg417** [comment]
附议ssrp 手动安装出现luci.model报错

**Comment by draco-china** [comment]
建议fork后自行修改呢，每个人需求都不一样，基本上都配置独立化了， 改起来也很方便
