### ISSUE TITLE
iStore无法使用

### ISSUE THREAD

**Issue by EdwardWu7** [draco-china/Draco-OpenWrt-GL-AX1800#8]
curl: (22) The requested URL returned error: 404

AX1800 AXT1800均是此现象

<img width="756" alt="image" src="https://user-images.githubusercontent.com/4351696/187130993-a01c2878-825d-416b-be79-4b093adcfce8.png">

**Comment by draco-china** [comment]
已经移除，里面的很多软件没有兼容
